services:
  postgres:
    image: postgres:latest  # Use the latest PostgreSQL image
    container_name: postgres_db  # Optional: name the container
    environment:
      POSTGRES_USER: eatsomewhere  # Set the PostgreSQL user
      POSTGRES_PASSWORD: eatsomewhere  # Set the PostgreSQL password
      POSTGRES_DB: eatsomewhere  # Set the PostgreSQL database name
    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432 (adjust as needed)
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data

volumes:
  dotnet_data:
    driver: local