// <auto-generated />
using System;
using EatSomewhere.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EatSomewhere.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250416140053_ingredients")]
    partial class ingredients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("AssemblyUser", b =>
                {
                    b.Property<string>("AssemblyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsersId")
                        .HasColumnType("TEXT");

                    b.HasKey("AssemblyId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("AssemblyUser");
                });

            modelBuilder.Entity("AssemblyUser1", b =>
                {
                    b.Property<string>("AdminsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assembly1Id")
                        .HasColumnType("TEXT");

                    b.HasKey("AdminsId", "Assembly1Id");

                    b.HasIndex("Assembly1Id");

                    b.ToTable("AssemblyUser1");
                });

            modelBuilder.Entity("AssemblyUser2", b =>
                {
                    b.Property<string>("Assembly2Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Assembly2Id", "PendingId");

                    b.HasIndex("PendingId");

                    b.ToTable("AssemblyUser2");
                });

            modelBuilder.Entity("EatSomewhere.Data.Assembly", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assemblies");
                });

            modelBuilder.Entity("EatSomewhere.Data.Food", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recipe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("EatSomewhere.Data.FoodEntry", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostPerPerson")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("PayedById");

                    b.ToTable("FoodEntries");
                });

            modelBuilder.Entity("EatSomewhere.Data.FoodParticipant", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FoodParticipant");
                });

            modelBuilder.Entity("EatSomewhere.Data.Ingredient", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("AssemblyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyId");

                    b.HasIndex("UserId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("EatSomewhere.Data.IngredientEntry", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientEntries");
                });

            modelBuilder.Entity("EatSomewhere.Data.Tag", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("EatSomewhere.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EatSomewhere.Users.UserSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidUnti")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("FoodEntryFoodParticipant", b =>
                {
                    b.Property<string>("FoodEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticipantsId")
                        .HasColumnType("TEXT");

                    b.HasKey("FoodEntryId", "ParticipantsId");

                    b.HasIndex("ParticipantsId");

                    b.ToTable("FoodEntryFoodParticipant");
                });

            modelBuilder.Entity("FoodIngredientEntry", b =>
                {
                    b.Property<string>("FoodId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientsId")
                        .HasColumnType("TEXT");

                    b.HasKey("FoodId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("FoodIngredientEntry");
                });

            modelBuilder.Entity("FoodTag", b =>
                {
                    b.Property<string>("FoodId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("FoodId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("FoodTag");
                });

            modelBuilder.Entity("AssemblyUser", b =>
                {
                    b.HasOne("EatSomewhere.Data.Assembly", null)
                        .WithMany()
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatSomewhere.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssemblyUser1", b =>
                {
                    b.HasOne("EatSomewhere.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AdminsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatSomewhere.Data.Assembly", null)
                        .WithMany()
                        .HasForeignKey("Assembly1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssemblyUser2", b =>
                {
                    b.HasOne("EatSomewhere.Data.Assembly", null)
                        .WithMany()
                        .HasForeignKey("Assembly2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatSomewhere.Users.User", null)
                        .WithMany()
                        .HasForeignKey("PendingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EatSomewhere.Data.Food", b =>
                {
                    b.HasOne("EatSomewhere.Data.Assembly", "Assembly")
                        .WithMany()
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assembly");
                });

            modelBuilder.Entity("EatSomewhere.Data.FoodEntry", b =>
                {
                    b.HasOne("EatSomewhere.Data.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId");

                    b.HasOne("EatSomewhere.Users.User", "PayedBy")
                        .WithMany()
                        .HasForeignKey("PayedById");

                    b.Navigation("Food");

                    b.Navigation("PayedBy");
                });

            modelBuilder.Entity("EatSomewhere.Data.Ingredient", b =>
                {
                    b.HasOne("EatSomewhere.Data.Assembly", "Assembly")
                        .WithMany("Ingredients")
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatSomewhere.Users.User", null)
                        .WithMany("Intolerances")
                        .HasForeignKey("UserId");

                    b.Navigation("Assembly");
                });

            modelBuilder.Entity("EatSomewhere.Data.IngredientEntry", b =>
                {
                    b.HasOne("EatSomewhere.Data.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("EatSomewhere.Data.Tag", b =>
                {
                    b.HasOne("EatSomewhere.Data.Assembly", "Assembly")
                        .WithMany()
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assembly");
                });

            modelBuilder.Entity("FoodEntryFoodParticipant", b =>
                {
                    b.HasOne("EatSomewhere.Data.FoodEntry", null)
                        .WithMany()
                        .HasForeignKey("FoodEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatSomewhere.Data.FoodParticipant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodIngredientEntry", b =>
                {
                    b.HasOne("EatSomewhere.Data.Food", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatSomewhere.Data.IngredientEntry", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodTag", b =>
                {
                    b.HasOne("EatSomewhere.Data.Food", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatSomewhere.Data.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EatSomewhere.Data.Assembly", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("EatSomewhere.Users.User", b =>
                {
                    b.Navigation("Intolerances");
                });
#pragma warning restore 612, 618
        }
    }
}
